import DebugContracts from '../../components/debug/DebugContracts';

export default function Debug() {
  return (
    <main className="min-h-screen bg-[#131416] text-white">
      <div className="max-w-4xl mx-auto px-4 my-[50px]">
        <h1 className="text-[28px] font-medium font-instrument text-center mb-2">Debug contracts</h1>
        <p className="text-[12px] font-mono text-[#908E8E] text-center mb-8">
          Raw access to every handoff function, generated by Scaffold Stacks.
        </p>
        <DebugContracts />
      </div>
    </main>
  );
}
